[request_definition]
r = sub, permission, obj, tier

[policy_definition]
p = sub, permission, eft

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = p.sub == r.sub && p.permission == r.permission && p.eft == allow && (r.obj.isEntity == false || r.obj.ownershipModel == "admin-owned" || r.obj.owner == r.sub || (r.obj.isPublic == true && r.tier == "read") || (r.tier == "read" && hasShare(r.obj.allShares, r.sub)) || (r.tier == "write" && hasShare(r.obj.editorShares, r.sub)))
